services:
  - type: web
    name: smart-notes-api
    runtime: python
    plan: free
    rootDir: ./backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    env:
      - key: ENVIRONMENT
        value: production

  - type: web
    name: smart-notes-frontend
    runtime: static
    plan: free
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    env:
      - key: VITE_ENVIRONMENT
        value: production
